apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: auth-service
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: auth-service
      app.kubernetes.io/instance: auth-service
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 8080
  egress:
    # DNS
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Postgres
    - ports:
        - protocol: TCP
          port: 5432
    # Redis
    - ports:
        - protocol: TCP
          port: 6379
